name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Swift Build
        run: swift build --package-path .
      - name: Swift Test
        run: swift test --package-path .
